<?php
namespace Sabahtalateh\Calc;
/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface CalculatorIf {
  /**
   * Ping if service alive
   * 
   */
  public function ping();
  /**
   * Calculate something
   * 
   * May throw exception
   * 
   * @param int $logid
   * @param \Sabahtalateh\Calc\CalcRequest $request
   * @return double
   * @throws \Sabahtalateh\Calc\CalculationException
   */
  public function calculate($logid, \Sabahtalateh\Calc\CalcRequest $request);
}

class CalculatorClient implements \Sabahtalateh\Calc\CalculatorIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function ping()
  {
    $this->send_ping();
    $this->recv_ping();
  }

  public function send_ping()
  {
    $args = new \Sabahtalateh\Calc\Calculator_ping_args();
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'ping', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('ping', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_ping()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\Sabahtalateh\Calc\Calculator_ping_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \Sabahtalateh\Calc\Calculator_ping_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    return;
  }

  public function calculate($logid, \Sabahtalateh\Calc\CalcRequest $request)
  {
    $this->send_calculate($logid, $request);
    return $this->recv_calculate();
  }

  public function send_calculate($logid, \Sabahtalateh\Calc\CalcRequest $request)
  {
    $args = new \Sabahtalateh\Calc\Calculator_calculate_args();
    $args->logid = $logid;
    $args->request = $request;
    $bin_accel = ($this->output_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'calculate', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('calculate', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_calculate()
  {
    $bin_accel = ($this->input_ instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\Sabahtalateh\Calc\Calculator_calculate_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \Sabahtalateh\Calc\Calculator_calculate_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    if ($result->e !== null) {
      throw $result->e;
    }
    throw new \Exception("calculate failed: unknown result");
  }

}

// HELPER FUNCTIONS AND STRUCTURES

class Calculator_ping_args extends TBase {
  static $_TSPEC;


  public function __construct() {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        );
    }
  }

  public function getName() {
    return 'Calculator_ping_args';
  }

  public function read($input)
  {
    return $this->_read('Calculator_ping_args', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('Calculator_ping_args', self::$_TSPEC, $output);
  }

}

class Calculator_ping_result extends TBase {
  static $_TSPEC;


  public function __construct() {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        );
    }
  }

  public function getName() {
    return 'Calculator_ping_result';
  }

  public function read($input)
  {
    return $this->_read('Calculator_ping_result', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('Calculator_ping_result', self::$_TSPEC, $output);
  }

}

class Calculator_calculate_args extends TBase {
  static $_TSPEC;

  /**
   * @var int
   */
  public $logid = null;
  /**
   * @var \Sabahtalateh\Calc\CalcRequest
   */
  public $request = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'logid',
          'type' => TType::I64,
          ),
        2 => array(
          'var' => 'request',
          'type' => TType::STRUCT,
          'class' => '\Sabahtalateh\Calc\CalcRequest',
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'Calculator_calculate_args';
  }

  public function read($input)
  {
    return $this->_read('Calculator_calculate_args', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('Calculator_calculate_args', self::$_TSPEC, $output);
  }

}

class Calculator_calculate_result extends TBase {
  static $_TSPEC;

  /**
   * @var double
   */
  public $success = null;
  /**
   * @var \Sabahtalateh\Calc\CalculationException
   */
  public $e = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::DOUBLE,
          ),
        1 => array(
          'var' => 'e',
          'type' => TType::STRUCT,
          'class' => '\Sabahtalateh\Calc\CalculationException',
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'Calculator_calculate_result';
  }

  public function read($input)
  {
    return $this->_read('Calculator_calculate_result', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('Calculator_calculate_result', self::$_TSPEC, $output);
  }

}

class CalculatorProcessor {
  protected $handler_ = null;
  public function __construct($handler) {
    $this->handler_ = $handler;
  }

  public function process($input, $output) {
    $rseqid = 0;
    $fname = null;
    $mtype = 0;

    $input->readMessageBegin($fname, $mtype, $rseqid);
    $methodname = 'process_'.$fname;
    if (!method_exists($this, $methodname)) {
      $input->skip(TType::STRUCT);
      $input->readMessageEnd();
      $x = new TApplicationException('Function '.$fname.' not implemented.', TApplicationException::UNKNOWN_METHOD);
      $output->writeMessageBegin($fname, TMessageType::EXCEPTION, $rseqid);
      $x->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
      return;
    }
    $this->$methodname($rseqid, $input, $output);
    return true;
  }

  protected function process_ping($seqid, $input, $output) {
    $args = new \Sabahtalateh\Calc\Calculator_ping_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \Sabahtalateh\Calc\Calculator_ping_result();
    $this->handler_->ping();
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'ping', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('ping', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
  protected function process_calculate($seqid, $input, $output) {
    $args = new \Sabahtalateh\Calc\Calculator_calculate_args();
    $args->read($input);
    $input->readMessageEnd();
    $result = new \Sabahtalateh\Calc\Calculator_calculate_result();
    try {
      $result->success = $this->handler_->calculate($args->logid, $args->request);
    } catch (\Sabahtalateh\Calc\CalculationException $e) {
      $result->e = $e;
    }
    $bin_accel = ($output instanceof TBinaryProtocolAccelerated) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($output, 'calculate', TMessageType::REPLY, $result, $seqid, $output->isStrictWrite());
    }
    else
    {
      $output->writeMessageBegin('calculate', TMessageType::REPLY, $seqid);
      $result->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
    }
  }
}

